[client]
toolbarMode = "minimal"

[ui]
hideTopBar = true

[theme]
base = "dark"
primaryColor = "#46c9ef"
backgroundColor = "#06101c"
secondaryBackgroundColor = "#0b1928"
textColor = "#f5f9fc"
borderColor = "#29455d"
showWidgetBorder = true
baseFontSize = 17

[layout]
topPadding = "4.5rem"
